---
rotten_tomatoes:
  base_models:
    tuning_dataset:
      path: rotten_tomatoes
      name: 
      # Train size must be an int  or None
      train_size: None
      eval_size: None
      limit_text_size: 750
      tokenize_truncation: 200
    names:
      - bert-base-uncased
      - albert-base-v2
      - distilbert-base-uncased
    tuning_params:
      LEARNING_RATE: 2e-5
      NUM_EPOCHS: 2
  adv_attacks:
    names:
      - A2TYoo2021
      - TextFoolerJin2019 
      - BAEGarg2019
#---
# testing_attacks:
#   base_models:
#     tuning_dataset:
#       path: glue
#       name: cola
#       # Train size must be an int  or None
#       train_size: 3000
#       eval_size: 1000
#     names:
#       - bert-base-uncased
#         #- albert-base-v2
#         #- distilbert-base-uncased
#     tuning_params:
#       LEARNING_RATE: 2e-5
#       NUM_EPOCHS: 1
#   adv_attacks:
#     names:
#       - A2TYoo2021
#       - TextFoolerJin2019 
#       - BAEGarg2019
