---
Experiment_1:
  base_models:
    tuning_dataset:
      path: glue
      name: cola
    names:
      - bert-base-uncased
      - albert-base-v2
      - distilbert-base-uncased
    tuning_params:
      LEARNING_RATE: 3
      NUM_EPOCHS: 3
  adv_attacks:
    names:
      - A2TYoo2021
      # - BERTAttackLi2020, 
# ---
# Experiment_Name2:
#   base_models:
#     tuning_dataset:
#       path: glue
#       name: cola
#     names:
#       - bert-base-uncased
#       - albert-base-v2
#       - distilbert-base-uncased
#     tuning_params:
#       LEARNING_RATE: 2e-5
#       NUM_EPOCHS: 3

