---
imdb_all_attacks_default:
  base_models:
    tuning_dataset:
      path: imdb
    names:
      - bert-base-uncased
      - albert-base-v2
      - distilbert-base-uncased
    tuning_params:
      LEARNING_RATE: 2e-5
      NUM_EPOCHS: 2
  adv_attacks:
    names:
      - A2TYoo2021
      - TextFoolerJin2019 
      - BAEGarg2019
# ---
# glue_all_attacks_default:
#   base_models:
#     tuning_dataset:
#       path: glue
#       nane: cola
#     names:
#       - bert-base-uncased
#       - albert-base-v2
#       - distilbert-base-uncased
#     tuning_params:
#       LEARNING_RATE: 2e-5
#       NUM_EPOCHS: 2
#   adv_attacks:
#     names:
#       - A2TYoo2021
#       - TextFoolerJin2019 
#       - BAEGarg2019
